name: docker

on:
  push:

env:
  IMAGE_FQDN: ghcr.io/kontextwork/zimbra-builder

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: actions/checkout@master
        with:
          name: ianw1974/zimbra-build-scripts
          token: ${{ secrets.my_pat }}
          path: zimbra-build-scripts
      - name: Build builder
        uses: docker/build-push-action@v3
        with:
          context: zimbra-build-scripts/
          platforms: linux/amd64
          push: false
          build-args: |
            # actually that's the distro to build ON and FOR
            RELEASE=ubuntu:20.04
          tags: |
            ${{ env.IMAGE_FQDN }}:builder
